### ISSUE TITLE
3 вопроса

### ISSUE THREAD

**Issue by edgiru** [kmaximv/Wi-Fi-Sensor#17]
1. Часы как то странно синхронизируются. (точнее не понятно когда). Включил NTP Enable перехожу на главную там время не правильно. доступ в интернет есть, все корректно. Жаль нет кнопки обновить вручную.
2. В прошивке используется понятие pin а не gpio так как модули бывают разные и пины у них разные может лучше использовать gpio? Подключил dht22 к D4 (gpio2) не работает, далее D1 и D2 это соответственно gpio5 и gpio4. Так и не заработало все по нулям.
3. wifi настройка. Не всегда срабатывает подключение. По умолчанию включено АР что бы изменить на АР-STA надо выбрать и нажать SAVE только потом выйдут настройки (первый раз вижу такую реализацию) далее вбиваю SSID вручную (хотя это жутко не удобно) жму Save сохраняется не всегда сразу иногда надо несколько раз нажать Save иногда не подключается ни к роутеру и не отображается стандартный SSID: ESP8266 приходиться опять перепрошивать бланком и опять накатывать прошивку. Вот такие странности.

NodeMCU 1.0 (ESP-12E)

**Comment by edgiru** [comment]
еще заметил то ли глюк то ли что. При включении всех датчиков в Sensors Configuration, то на главной странице пропадают значения.
![default](https://cloud.githubusercontent.com/assets/4624056/19418343/a7a3d91c-93ca-11e6-8db4-255de46867fe.JPG)

**Comment by kmaximv** [comment]
1. Сейчас переписываю под обновленную библиотеку, на днях выложу обновление.
2. По пинам не понял вопроса. Если указываем в прошивке pin = 2 это и есть gpio2. По dht22, постараюсь проверить его работу на последней прошивке.
3. Про wi-fi, согласен, неудобная настойка. Просто в вебе не силен, со временем буду переделывать.

**Comment by edgiru** [comment]
Спасибо что реагируете и не забрасываете проект. По пинам 
![nodemcu_pinout](https://cloud.githubusercontent.com/assets/4624056/19432180/0c278764-9464-11e6-950b-4201b6ae80ee.png)
Подключил DHT22 к контакту D4 (gpio2) в настройках на модуле вместо pin2 указал pin1 и заработало.  Получается в прошивке все же не так как вы написали. Pin1 - это gpio2 судя про распиновке.

**Comment by kmaximv** [comment]
Странно, у меня на ESP12F используются 2,12,13,14 пины, и все совпадают. Похоже на вашей плате что-то напутали...

**Comment by edgiru** [comment]
и еще один момент в меню похоже у Вас не прописана эта страница. пасхальное яйцо :)))
![default](https://cloud.githubusercontent.com/assets/4624056/19446975/1b0a684c-94a4-11e6-8438-bce8e8ad8c2a.JPG)

**Comment by kmaximv** [comment]
Это для будущего проекта автоматического полива и подсветки растений. Пока не доделал

**Comment by kmaximv** [comment]
Обновил функцию NTP клиента. Скачать обновленную библиотеку можно с Вики.

Единственный момент, NTP сервер желательно указать ip-адресом а не DNS именем.
В родной библиотеке Arduino IDE **wifi_drv.cpp** очень криво сделан resolve dns name. Если он не находит имя в DNS, то вешает ESP на 10 секунд, после чего до неё уже не достучаться. С ip-адресом таких проблем нет.
Пока не знаю как обойти эту проблему...

**Comment by edgiru** [comment]
работает! а стандартный  NTP клиент которой в ардуино ide есть не подходит? что там меняется? еще вопрос а как у Вас высчитывается напряжение на ноге ADC? показывает: 2.74V. померил тестером: 3,31в. Тестер конечно китайский но стабилизаторы не плохие AMS1117 причем датчики посадил даже на отдельный стабилизатор AMS1117 и электролит поставил хороший по питанию, вроде не должно быть просадки.

**Comment by kmaximv** [comment]
Стандартный NTP клиент взят за основу. Под себя добавил функцию смены NTP сервера, проверку доступности сервера перед отправкой пакета. Также убрал цикл, который ждал ответ от сервера целую секунду. 

Для снятия напряжения используется стандартная функция. Ниже весь код, который используется для этого

```
ADC_MODE(ADC_VCC);
float voltage_float;
int voltage = ESP.getVcc();
voltage_float = voltage / 1000.0; 
```

При этом нога ADC не должна быть к чему либо подключена. Посмотрите, может на вашей плате на нее что-нибудь повесили?
