### ISSUE TITLE
Добавить кнопку сброса настроек на стандартные

### ISSUE THREAD

**Issue by kmaximv** [kmaximv/Wi-Fi-Sensor#18]

**Comment by edgiru** [comment]
согласен но если web интерфейс не грузится как сбросить настройки? в wifi-iot.com проекте решили это долгим нажатием на ресет при этом модуль входит в специальный режим.

**Comment by kmaximv** [comment]
Добавил эту функцию.
Сброс настроек производится при включении модуля, при зажатой кнопке в течении 3 секунд.
Чтобы сработало, нужно кнопкой подтянуть reset_pin(gpio2) к земле.

Через веб интерфейс смысла делать наверно нет.
