### ISSUE TITLE
У Вас тоже так же?

### ISSUE THREAD

**Issue by edgiru** [kmaximv/Wi-Fi-Sensor#20]
Я думал esp-01 только глючные, а оказывается все модули не стабильны. У Вас тоже так или мне не везет с модулями?
![default](https://cloud.githubusercontent.com/assets/4624056/19839819/fed25bde-9ef9-11e6-96aa-49ece35ebe6b.JPG)

**Comment by kmaximv** [comment]
Бывает такое при слабом Wi-Fi сигнале. Также можно включить дебаг и посмотреть по UART чем ESP занимается в это время.

**Comment by kmaximv** [comment]
На день оставлял пинги на пару ESP, ни одной потери пакетов

```
--- 192.168.2.101 ping statistics ---
52810 packets transmitted, 52810 received, +24 duplicates, 0% packet loss, time 52882350ms
rtt min/avg/max/mdev = 2.033/6.972/2291.213/22.043 ms, pipe 3
```

```
--- 192.168.2.102 ping statistics ---
52810 packets transmitted, 52810 received, +38 duplicates, 0% packet loss, time 52886204ms
rtt min/avg/max/mdev = 0.950/2.058/63.396/2.225 ms
```

**Comment by edgiru** [comment]
странно. у меня еще включен mqtt передача на cloudmqtt. буду пробовать перепрошивать.

**Comment by kmaximv** [comment]
Выяснил что такое поведение у ESP возникает по нескольким причинам:
1. ESP не может достучаться до MQTT сервера (неправильный ip, плохая связь по wi-fi и т.д.)
2. На ESP настроена авторизация MQTT, а на MQTT сервере нет (или наоборот)

Не получается настроить нормальную работу ESP при нештатной ситуации с сервером MQTT. Проблема в библиотеке Pubsubclient. 

Сейчас тестирую другую библиотеку, вроде ведет себя стабильно в проблемных ситуациях. Переход займет какое-то время...

**Comment by edgiru** [comment]
сигнал wifi отсекаю т.к. точка доступа стоит в 60см от esp. Причем точка не плохая на базе openwrt не стабильной работы не замечено за несколько лет эксплуатации. Про mqtt возможно.

**Comment by kmaximv** [comment]
Заменил библиотеку, можете проверить как теперь работает?

**Comment by edgiru** [comment]
Уже более стабильно работает. пинги маленькие. Спасибо
