### ISSUE TITLE
Нагрузки

### ISSUE THREAD

**Issue by edgiru** [kmaximv/Wi-Fi-Sensor#22]
Я так понял схема с низковольтными нагрузками выдерживает до 15А и соответственно до 180Вт, схема с высоковольтной нагрузкой выдерживает до 8А и напряжение пиковое до 600В при 230В соответственно 1.84кВт. Все верно? Можно ли эти цифры указать в wiki для интересующихся проектом. Ещё добавлю: S202T02 - 2A(460Вт), S216S02 - 16A(3.6кВт)

**Comment by kmaximv** [comment]
Да, только нужно позаботиться об охлаждении силовых элементов.
Но я никогда не гружу по полной, лучше всегда оставлять запас.

**Comment by edgiru** [comment]
Ещё хотел спросить как на счёт шима в ваших схемах? В низковольтной и высоковольтной схеме хорошо бы применять плавное включение и плавное отключение и регулировку мощности.

**Comment by kmaximv** [comment]
Плавное включение/выключение давно есть Configure => ESP => Smooth Enable
На счет регулировки мощности надо подумать.

**Comment by edgiru** [comment]
Еще кое что. На wiki в "Железе" у Вас IRLU024N а на схеме IRF530

**Comment by kmaximv** [comment]
В принципе туда много чего можно поставить, ставлю то, что есть под рукой. Главное чтобы подходили по параметрам.
