### ISSUE TITLE
telegram bot и другие идеи

### ISSUE THREAD

**Issue by edgiru** [kmaximv/Wi-Fi-Sensor#23]
Предлагаю добавить https://github.com/Gianbacchio/ESP8266-TelegramBot думаю будет удобно совместно с mqtt.
Еще была идея о связке модулей, т.е. к примеру к модулю №1 подключены датчики уличные (модуль находится на улице работающий от питания аккумулятора, ионистора, солн. батареи) и информация вся передается или на какой то сервер умного дома или на mqtt или к примеру на другой модуль №2 к которому подключен к примеру lcd.

**Comment by kmaximv** [comment]
Так как я использую OpenHAB, то все эти функции можно реализовать на нём. Поэтому переносить этот функционал в прошивку не планирую.
