### ISSUE TITLE
Ошибка при компиляции

### ISSUE THREAD

**Issue by annak1n** [kmaximv/Wi-Fi-Sensor#28]
**Добрый день пробовал скомпилировать в IDE 1.6.13 и также пробовал в 1.8.1
Но ошибка одна и таже:**
`C:\Users\Annak1n\AppData\Local\Temp\arduino_modified_sketch_839819\esp_sensor.ino: In function 'void setup()':

esp_sensor:1449: error: invalid conversion from 'bool (*)()' to 'timer_callback {aka void (*)()}' [-fpermissive]

   timer.setInterval(60000, MqttConnect);

                                       ^

In file included from C:\Users\Annak1n\AppData\Local\Temp\arduino_modified_sketch_839819\esp_sensor.ino:15:0:

D:\Arduino\Arduino\libraries\SimpleTimer/SimpleTimer.h:56:9: error:   initializing argument 2 of 'int SimpleTimer::setInterval(long int, timer_callback)' [-fpermissive]

     int setInterval(long d, timer_callback f);

         ^

esp_sensor:1450: error: invalid conversion from 'bool (*)()' to 'timer_callback {aka void (*)()}' [-fpermissive]

   timer.setInterval(atoi(JConf.publish_delay) * 1000, MqttPubData);

                                                                  ^

In file included from C:\Users\Annak1n\AppData\Local\Temp\arduino_modified_sketch_839819\esp_sensor.ino:15:0:

D:\Arduino\Arduino\libraries\SimpleTimer/SimpleTimer.h:56:9: error:   initializing argument 2 of 'int SimpleTimer::setInterval(long int, timer_callback)' [-fpermissive]

     int setInterval(long d, timer_callback f);

         ^`

**Comment by kmaximv** [comment]
Проблема в библиотеке SimpleTimer, откуда вы её ставили? Попробуйте удалить, а затем скопировать библиотеку с этого проекта.
Все библиотеки, которые нужны для этого проекта, находятся здесь:
https://github.com/kmaximv/Wi-Fi-Sensor/tree/master/esp_sensor/libraries
С другими версиями библиотек может не работать

**Comment by annak1n** [comment]
Спасибо помогло.
