### ISSUE TITLE
Подключение к модулю по Wi-Fi

### ISSUE THREAD

**Issue by artyrn** [kmaximv/Wi-Fi-Sensor#29]
Прошил модуль по инструкции в Wiki через ардуино, перегрузил модуль к моей сети  Wi-Fi он подключится не может (нужен пароль), модуль создал АП, но она зарытая требует пароль, в  Wiki не сказано какай пароль вводить.

**Comment by kmaximv** [comment]
Пароль можете посмотреть здесь:
https://github.com/kmaximv/Wi-Fi-Sensor/blob/master/esp_sensor/json_config.h#L26

**Comment by artyrn** [comment]
Спасибо.
