### ISSUE TITLE
Прошивка ESP по воздуху.

### ISSUE THREAD

**Issue by annak1n** [kmaximv/Wi-Fi-Sensor#30]
Не получается прошиться по воздуху, компилирую в IDE потом копирую bin фаил из папки тэмп и пытаюсь прошиться и пишет FAIL
И после попытки обновления по воздуху сбрасываются все настройки ЕСПшки, типа настроки датчиков и прочей дряни.

**Comment by kmaximv** [comment]
Сколько памяти на ESP?

**Comment by annak1n** [comment]
21:37:38 ESP: Sketch size: 385920
21:37:38 ESP: Free size: 49152
21:37:38 ESP: Free memory: 23136
Вот что пишет в консоли ЕСПшки

**Comment by kmaximv** [comment]
Я про объем flash памяти. Эта прошивка писалась под ESP 12F, на которой 4MB flash. Других плат у меня нет, так что проверить не на чем.
UPD: 
21:37:38 ESP: Free size: 49152
Здесь недостаточно места для прошивки по воздуху. Прошивка весит 385Kb, а свободно 49Кb.

**Comment by annak1n** [comment]
Сори дружище мой косяк был, я не правельно в Arduino IDE выставил размер памяти и оно форматировало ЕСПшку как 512кб ))
Шас начал прикручивать датчик тока SCT 013 и датчик напряжения из этой темы:
http://majordomo.smartliving.ru/forum/viewtopic.php?f=8&t=73
