### ISSUE TITLE
работа с PZEM

### ISSUE THREAD

**Issue by artyrn** [kmaximv/Wi-Fi-Sensor#32]
При работе с PZEM и не возможностью считать с него показания, по mqtt передаются последние считанные показания, ситуация конечно не однозначная, если просто обнулить значения то можно подумать что в сети пропало напряжение, видимо нужно еще передавать флаг есть  связь с PZEM  или нет.

**Comment by kmaximv** [comment]
Думаю, будет достаточно прекращать передачу показаний, если PZEM отваливается. Не хочется заводить лишние сущности, вроде флагов.

**Comment by artyrn** [comment]
>>Думаю, будет достаточно прекращать передачу показаний, если PZEM отваливается.
можно и так

**Comment by artyrn** [comment]
А на страничке самого устройства тогда как? Сейчас там также последнее считанное показание.

**Comment by kmaximv** [comment]
Добавил коммит:
[af6678a](https://github.com/kmaximv/Wi-Fi-Sensor/commit/af6678a02c04dbd81838fe3918ca28f4878cd82c)
На веб-странице показания будут заменяться на "none".

**Comment by artyrn** [comment]
Прошил новую версию. Спасибо за оперативную доработку.
Баг репорт. После пропадания связи с PZEM как и задумывалось по mqtt перестают передаваться топики с показаниями,  но в вэбе устройства в полях с текущими показаниями NONE появляется только в одном из полей (видимо в том по которому не удалось получить ответа от PZEM), наверное нужно что бы NONE появилось во всех полях.

**Comment by kmaximv** [comment]
Внёс изменения, можете проверить?

**Comment by artyrn** [comment]
Проверил работает. NONE в вэбе появляются, правда не во всех полях сразу, а видимо как не может считать данный показатель, но это вроде как  и логично.

**Comment by artyrn** [comment]
Обратил внимание, что если связь с PZEM восстановилась то значения которые еще не считались начинают передаваться по mqtt в виде none, вроде не страшно просто перед записью в базу данных нужно быть готовым что там может быть none вместо цифирок.

**Comment by kmaximv** [comment]
Добавил проверку, теперь NONE не должно попадать в MQTT

**Comment by artyrn** [comment]
Сообщения о PZEM по mqtt пропадают если есть хотя бы одно NONE и возобновляются когда все NONE пропали. Вроде как нормально получилось. Спасибо за проделанную работу.

**Comment by kmaximv** [comment]
Хорошо, тогда закрываю issue.
