### ISSUE TITLE
Документация (Manual)

### ISSUE THREAD

**Issue by ZigFisher** [kmaximv/Wi-Fi-Sensor#8]
Напишите, пожалуйста, на титульной странице дополнительно информацию:
- WiFi SSID и пароль (я понимаю, что можно в исходнике посмотреть)
- пример прошивки модуля любой программой с указанием адреса (текстовая строка)

**Comment by ZigFisher** [comment]
При прошивке модулей (пробовалось на разных) по стартовому адресу собранными бинарными прошивками (пробовались обе), получаем постоянную перезагрузку:

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1264, room 16 
tail 0
chksum 0x42
csum 0x42
~ld

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1264, room 16 
tail 0
chksum 0x42
csum 0x42
~ld

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

**Comment by kmaximv** [comment]
Прошил с помощью esptool, обе прошивки нормально прошились командой: 
`C:\Soft/esptool.exe -vv -cd nodemcu -cb 115200 -cp COM6 -ca 0x00000 -cf С:\Soft/esp_sensor.ino.nodemcu.bin`

Утилиту прикреплю в релизах, чтобы не искать.
Сколько флеш памяти на ваших модулях?

**Comment by ZigFisher** [comment]
Приветствую !
Спасибо за учёт пожеланий и оперативное их выполнение ! ;)

У меня еще предложение к вам, добавить в релиз esptool под Linux и пример команды прошивки
./esptool -vv -cd nodemcu -cb 115200 -cp /dev/ttyUSB0 -ca 0x00000 -cf esp_sensor.ino.bin

Значит так, модули у меня разные на радиокружке, пробовал я лично прошивать, после того как у пионеров не получилось, и NodeMCU и WeMos и AiThinker модули, с флешками разными, от 512к до 4мБ. Результат, тот что выше.
Однако, до этого у нас использовалась утилита под Linux esptool.py, писанная на Питоне. Вот с ней прошиться ни в какую, как только не пробовали. Затем скачали с GitHub Си-шный вариант esptool, собрали, и о чудо !, прошились все модули удачно. 
Не думаю что это имеет смысл описывать, однако, вам как разработчику, это на заметку, если будут вопросы "не работает".

В общем, железка вышла на связь. Сейчас попробуем настроить и отпишусь.

**Comment by kmaximv** [comment]
Привет!
Можете кинуть ссылку на рабочий вариант esptool под Linux?

**Comment by ZigFisher** [comment]
Тут - https://github.com/igrr/esptool-ck/releases

Еще вопрос - вы планируете развивать свой проект, если да, то в каком направлении или пока особо ничего не планируется в ближайшее время ?

**Comment by kmaximv** [comment]
Спасибо за ссылку!

Сейчас делаю управление с ESP  ардуиной по UART, понадобилось несколько аналоговых портов для проекта автоматического полива растений. Уже наладил управление, осталось написать логику и оформить веб-страницу.

![apins](https://cloud.githubusercontent.com/assets/1822314/12866773/6d9a7308-cd04-11e5-9c54-235f19cee77e.png)

**Comment by ZigFisher** [comment]
Угу. Выглядит заманчиво ;)
Вижу, документация постоянно обновляется. Это очень хорошо.
Маякните, пожалуйста, мне на почту flyrouter(!)гугломаил.ком - есть несколько вопросов.
Спасибо.  Закрываю Issue.
